# Generated by Django 2.2.6 on 2019-11-03 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='book_author', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='book',
            field=models.ManyToManyField(related_name='book_rating', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ManyToManyField(related_name='reader', to=settings.AUTH_USER_MODEL),
        ),
    ]
