# Generated by Django 2.2.6 on 2019-11-23 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='average_rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
