# Generated by Django 2.2.6 on 2019-11-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20191123_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='average_rating',
        ),
    ]
