# Generated by Django 2.2.6 on 2019-11-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_favouritebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.ManyToManyField(to='books.Category'),
        ),
    ]
